baseURL = "https://www.sandracervantes.com/"
languageCode = "en-us"
summaryLength = 30
[[menu.main]]
name = "Featured Properties"
parent = "Property Search"
url = "https://sandracervantes.idxhome.com/featured/133262"
weight = 1
[[menu.main]]
name = "Login"
url = "https://sandracervantes.idxhome.com/homesearch/145641"
weight = 8
[[menu.main]]
name = "Resources"
weight = 5
[[menu.main]]
name = "Valuation Request"
parent = "Sellers"
url = "https://www.sandracervantes.com/home-value-request"
weight = 1
[[menu.main]]
name = "Sellers"
weight = 4
[[menu.main]]
name = "Buyers"
weight = 3
[[menu.main]]
name = "Open Homes"
parent = "Property Search"
url = "https://sandracervantes.idxhome.com/openhomes/133262"
weight = 4
[[menu.main]]
name = "Advanced Search"
parent = "Property Search"
url = "https://sandracervantes.idxhome.com/listing/search/advanced/133262/13"
weight = 3
[[menu.main]]
name = "Search"
parent = "Property Search"
url = "https://sandracervantes.idxhome.com/homesearch/133262"
weight = 2
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 7
[[menu.main]]
name = "Property Search"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[taxonomies]
category = "categories"
city = "city"
status = "status"
tag = "tags"
zip = "zip"
